const ROUTES = {
  HOME: "/",
  ABOUT: "/about",
  REGISTER: "/register",
  LOGIN: "/login",
  EDITCARD: "/edit-card",
  ABOUTCARD: "/AboutCardPage",
  CREATECARD: "/CreateCardPage",
  SANDBOX: "/sandbox",
  FAVORITE: "/favorite",
  FOOTER: "/footer",
  MYCARD: "/mycard",
  SANDBOX: "/sandbox",
  CARD: "/card",
  PROFILE: "/ProfilePage",
  HEADERS: "/header",
  FAVORITEADMIN: "/favoriteAdmin",
  FORGOTPASSWORD: "/forgot-password",
  RESETPASSWORD: "/reset-password",
};
export default ROUTES;
